Repository aws/amazon-ecs-cli, pull requests merged in 2019-10, with the labels that each got.

#937 Print out verbose messages for credential chain errors
  ecs-cli/modules/cli/local/secrets/clients/clients.go
  ecs-cli/modules/clients/aws/cloudwatchlogs/client.go
  ecs-cli/modules/config/config_v1.go
Labels: Enhancement

#935 Fix 933
  ecs-cli/modules/cli/local/secrets/clients/clients.go
  ecs-cli/modules/cli/local/secrets/clients/clients_test.go
Labels: Bug Fix, Pending push

#931 Add additional logging to integ tests
  ecs-cli/integ/cmd/compose.go
Labels: Pending release
